version: '3'
services:
  magic-api:
    build: .
    environment:
      PORT: "5001"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_PASSWORD: "password"
      DB_USER: "postgres"
      DB_NAME: "magic"
    ports:
    - "5001:5001"
  postgres:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "magic"