// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetWaitTimesRequest struct {
	// Types that are valid to be assigned to Criteria:
	//	*GetWaitTimesRequest_ParkId
	//	*GetWaitTimesRequest_RideId
	Criteria             isGetWaitTimesRequest_Criteria `protobuf_oneof:"criteria"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetWaitTimesRequest) Reset()         { *m = GetWaitTimesRequest{} }
func (m *GetWaitTimesRequest) String() string { return proto.CompactTextString(m) }
func (*GetWaitTimesRequest) ProtoMessage()    {}
func (*GetWaitTimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *GetWaitTimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWaitTimesRequest.Unmarshal(m, b)
}
func (m *GetWaitTimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWaitTimesRequest.Marshal(b, m, deterministic)
}
func (m *GetWaitTimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWaitTimesRequest.Merge(m, src)
}
func (m *GetWaitTimesRequest) XXX_Size() int {
	return xxx_messageInfo_GetWaitTimesRequest.Size(m)
}
func (m *GetWaitTimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWaitTimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWaitTimesRequest proto.InternalMessageInfo

type isGetWaitTimesRequest_Criteria interface {
	isGetWaitTimesRequest_Criteria()
}

type GetWaitTimesRequest_ParkId struct {
	ParkId string `protobuf:"bytes,1,opt,name=park_id,json=parkId,proto3,oneof"`
}

type GetWaitTimesRequest_RideId struct {
	RideId string `protobuf:"bytes,2,opt,name=ride_id,json=rideId,proto3,oneof"`
}

func (*GetWaitTimesRequest_ParkId) isGetWaitTimesRequest_Criteria() {}

func (*GetWaitTimesRequest_RideId) isGetWaitTimesRequest_Criteria() {}

func (m *GetWaitTimesRequest) GetCriteria() isGetWaitTimesRequest_Criteria {
	if m != nil {
		return m.Criteria
	}
	return nil
}

func (m *GetWaitTimesRequest) GetParkId() string {
	if x, ok := m.GetCriteria().(*GetWaitTimesRequest_ParkId); ok {
		return x.ParkId
	}
	return ""
}

func (m *GetWaitTimesRequest) GetRideId() string {
	if x, ok := m.GetCriteria().(*GetWaitTimesRequest_RideId); ok {
		return x.RideId
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetWaitTimesRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetWaitTimesRequest_ParkId)(nil),
		(*GetWaitTimesRequest_RideId)(nil),
	}
}

type GetWaitTimesResponse struct {
	WaitTime             []*WaitTime `protobuf:"bytes,1,rep,name=wait_time,json=waitTime,proto3" json:"wait_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetWaitTimesResponse) Reset()         { *m = GetWaitTimesResponse{} }
func (m *GetWaitTimesResponse) String() string { return proto.CompactTextString(m) }
func (*GetWaitTimesResponse) ProtoMessage()    {}
func (*GetWaitTimesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *GetWaitTimesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWaitTimesResponse.Unmarshal(m, b)
}
func (m *GetWaitTimesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWaitTimesResponse.Marshal(b, m, deterministic)
}
func (m *GetWaitTimesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWaitTimesResponse.Merge(m, src)
}
func (m *GetWaitTimesResponse) XXX_Size() int {
	return xxx_messageInfo_GetWaitTimesResponse.Size(m)
}
func (m *GetWaitTimesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWaitTimesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWaitTimesResponse proto.InternalMessageInfo

func (m *GetWaitTimesResponse) GetWaitTime() []*WaitTime {
	if m != nil {
		return m.WaitTime
	}
	return nil
}

type WaitTime struct {
	ParkId               string   `protobuf:"bytes,1,opt,name=park_id,json=parkId,proto3" json:"park_id,omitempty"`
	RideId               string   `protobuf:"bytes,2,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	WaitTime             int32    `protobuf:"varint,3,opt,name=wait_time,json=waitTime,proto3" json:"wait_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaitTime) Reset()         { *m = WaitTime{} }
func (m *WaitTime) String() string { return proto.CompactTextString(m) }
func (*WaitTime) ProtoMessage()    {}
func (*WaitTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *WaitTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitTime.Unmarshal(m, b)
}
func (m *WaitTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitTime.Marshal(b, m, deterministic)
}
func (m *WaitTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitTime.Merge(m, src)
}
func (m *WaitTime) XXX_Size() int {
	return xxx_messageInfo_WaitTime.Size(m)
}
func (m *WaitTime) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitTime.DiscardUnknown(m)
}

var xxx_messageInfo_WaitTime proto.InternalMessageInfo

func (m *WaitTime) GetParkId() string {
	if m != nil {
		return m.ParkId
	}
	return ""
}

func (m *WaitTime) GetRideId() string {
	if m != nil {
		return m.RideId
	}
	return ""
}

func (m *WaitTime) GetWaitTime() int32 {
	if m != nil {
		return m.WaitTime
	}
	return 0
}

type GetAttractionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAttractionsRequest) Reset()         { *m = GetAttractionsRequest{} }
func (m *GetAttractionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAttractionsRequest) ProtoMessage()    {}
func (*GetAttractionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *GetAttractionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAttractionsRequest.Unmarshal(m, b)
}
func (m *GetAttractionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAttractionsRequest.Marshal(b, m, deterministic)
}
func (m *GetAttractionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAttractionsRequest.Merge(m, src)
}
func (m *GetAttractionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAttractionsRequest.Size(m)
}
func (m *GetAttractionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAttractionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAttractionsRequest proto.InternalMessageInfo

type GetAttractionsResponse struct {
	Attraction           []*Attraction `protobuf:"bytes,1,rep,name=attraction,proto3" json:"attraction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetAttractionsResponse) Reset()         { *m = GetAttractionsResponse{} }
func (m *GetAttractionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAttractionsResponse) ProtoMessage()    {}
func (*GetAttractionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *GetAttractionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAttractionsResponse.Unmarshal(m, b)
}
func (m *GetAttractionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAttractionsResponse.Marshal(b, m, deterministic)
}
func (m *GetAttractionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAttractionsResponse.Merge(m, src)
}
func (m *GetAttractionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAttractionsResponse.Size(m)
}
func (m *GetAttractionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAttractionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAttractionsResponse proto.InternalMessageInfo

func (m *GetAttractionsResponse) GetAttraction() []*Attraction {
	if m != nil {
		return m.Attraction
	}
	return nil
}

type Attraction struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attraction) Reset()         { *m = Attraction{} }
func (m *Attraction) String() string { return proto.CompactTextString(m) }
func (*Attraction) ProtoMessage()    {}
func (*Attraction) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *Attraction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attraction.Unmarshal(m, b)
}
func (m *Attraction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attraction.Marshal(b, m, deterministic)
}
func (m *Attraction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attraction.Merge(m, src)
}
func (m *Attraction) XXX_Size() int {
	return xxx_messageInfo_Attraction.Size(m)
}
func (m *Attraction) XXX_DiscardUnknown() {
	xxx_messageInfo_Attraction.DiscardUnknown(m)
}

var xxx_messageInfo_Attraction proto.InternalMessageInfo

func (m *Attraction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Attraction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GetWaitTimesRequest)(nil), "proto.GetWaitTimesRequest")
	proto.RegisterType((*GetWaitTimesResponse)(nil), "proto.GetWaitTimesResponse")
	proto.RegisterType((*WaitTime)(nil), "proto.WaitTime")
	proto.RegisterType((*GetAttractionsRequest)(nil), "proto.GetAttractionsRequest")
	proto.RegisterType((*GetAttractionsResponse)(nil), "proto.GetAttractionsResponse")
	proto.RegisterType((*Attraction)(nil), "proto.Attraction")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcb, 0x4a, 0xc3, 0x40,
	0x14, 0x86, 0x4d, 0x6a, 0x6a, 0x72, 0x94, 0x8a, 0xe3, 0x25, 0x35, 0x55, 0x08, 0x59, 0x65, 0x21,
	0x45, 0xeb, 0x13, 0x28, 0x42, 0x2c, 0xd2, 0x4d, 0x10, 0x8a, 0xab, 0x32, 0x26, 0x83, 0x1c, 0x24,
	0x17, 0x27, 0x47, 0xfa, 0x38, 0xbe, 0xaa, 0x24, 0x9d, 0x5c, 0x1a, 0xeb, 0x2a, 0xc3, 0xff, 0xfd,
	0x9c, 0xf9, 0xe6, 0x04, 0x2c, 0x9e, 0xe3, 0x34, 0x97, 0x19, 0x65, 0xcc, 0xa8, 0x3e, 0xde, 0x12,
	0x4e, 0x03, 0x41, 0x4b, 0x8e, 0xf4, 0x8a, 0x89, 0x28, 0x42, 0xf1, 0xf5, 0x2d, 0x0a, 0x62, 0x97,
	0x70, 0x90, 0x73, 0xf9, 0xb9, 0xc2, 0x78, 0xac, 0xb9, 0x9a, 0x6f, 0x3d, 0xef, 0x85, 0xc3, 0x32,
	0x98, 0xc7, 0x25, 0x92, 0x18, 0x8b, 0x12, 0xe9, 0x35, 0x2a, 0x83, 0x79, 0xfc, 0x08, 0x60, 0x46,
	0x12, 0x49, 0x48, 0xe4, 0xde, 0x13, 0x9c, 0x6d, 0x0f, 0x2e, 0xf2, 0x2c, 0x2d, 0x04, 0xbb, 0x01,
	0x6b, 0xcd, 0x91, 0x56, 0x84, 0x89, 0x18, 0x6b, 0xee, 0xc0, 0x3f, 0x9c, 0x1d, 0x6f, 0x94, 0xa6,
	0x75, 0x39, 0x34, 0xd7, 0xea, 0xe4, 0xbd, 0x81, 0x59, 0xa7, 0xcc, 0xee, 0x39, 0x35, 0x46, 0x76,
	0xcf, 0xa8, 0xf6, 0x61, 0x93, 0xee, 0x5d, 0x03, 0x57, 0xf3, 0x8d, 0xce, 0x68, 0x1b, 0xce, 0x03,
	0x41, 0x0f, 0x44, 0x92, 0x47, 0x84, 0x59, 0x5a, 0xbf, 0xdd, 0x7b, 0x81, 0x8b, 0x3e, 0x50, 0xee,
	0x77, 0x00, 0xbc, 0x89, 0x95, 0xfc, 0x89, 0x92, 0x6f, 0xfb, 0x61, 0xa7, 0xe4, 0xdd, 0x02, 0xb4,
	0x84, 0x8d, 0x40, 0x6f, 0xec, 0x75, 0x8c, 0x19, 0x83, 0xfd, 0x94, 0x27, 0x42, 0x69, 0x57, 0xe7,
	0xd9, 0x8f, 0x06, 0xc6, 0x82, 0x7f, 0x60, 0xc4, 0x02, 0x38, 0xea, 0xae, 0x90, 0x39, 0xea, 0xaa,
	0x1d, 0x3f, 0xcc, 0x99, 0xec, 0x64, 0xca, 0x7b, 0x01, 0xa3, 0xed, 0x17, 0xb1, 0xab, 0xb6, 0xfe,
	0x77, 0x03, 0xce, 0xf5, 0x3f, 0x74, 0x33, 0xee, 0x7d, 0x58, 0xd1, 0xfb, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf4, 0x55, 0xee, 0x0f, 0x4e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MagicClient is the client API for Magic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MagicClient interface {
	GetWaitTimes(ctx context.Context, in *GetWaitTimesRequest, opts ...grpc.CallOption) (*GetWaitTimesResponse, error)
	GetAttractions(ctx context.Context, in *GetAttractionsRequest, opts ...grpc.CallOption) (*GetAttractionsResponse, error)
}

type magicClient struct {
	cc *grpc.ClientConn
}

func NewMagicClient(cc *grpc.ClientConn) MagicClient {
	return &magicClient{cc}
}

func (c *magicClient) GetWaitTimes(ctx context.Context, in *GetWaitTimesRequest, opts ...grpc.CallOption) (*GetWaitTimesResponse, error) {
	out := new(GetWaitTimesResponse)
	err := c.cc.Invoke(ctx, "/proto.Magic/GetWaitTimes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicClient) GetAttractions(ctx context.Context, in *GetAttractionsRequest, opts ...grpc.CallOption) (*GetAttractionsResponse, error) {
	out := new(GetAttractionsResponse)
	err := c.cc.Invoke(ctx, "/proto.Magic/GetAttractions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MagicServer is the server API for Magic service.
type MagicServer interface {
	GetWaitTimes(context.Context, *GetWaitTimesRequest) (*GetWaitTimesResponse, error)
	GetAttractions(context.Context, *GetAttractionsRequest) (*GetAttractionsResponse, error)
}

// UnimplementedMagicServer can be embedded to have forward compatible implementations.
type UnimplementedMagicServer struct {
}

func (*UnimplementedMagicServer) GetWaitTimes(ctx context.Context, req *GetWaitTimesRequest) (*GetWaitTimesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWaitTimes not implemented")
}
func (*UnimplementedMagicServer) GetAttractions(ctx context.Context, req *GetAttractionsRequest) (*GetAttractionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttractions not implemented")
}

func RegisterMagicServer(s *grpc.Server, srv MagicServer) {
	s.RegisterService(&_Magic_serviceDesc, srv)
}

func _Magic_GetWaitTimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWaitTimesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicServer).GetWaitTimes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Magic/GetWaitTimes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicServer).GetWaitTimes(ctx, req.(*GetWaitTimesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Magic_GetAttractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttractionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicServer).GetAttractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Magic/GetAttractions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicServer).GetAttractions(ctx, req.(*GetAttractionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Magic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Magic",
	HandlerType: (*MagicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWaitTimes",
			Handler:    _Magic_GetWaitTimes_Handler,
		},
		{
			MethodName: "GetAttractions",
			Handler:    _Magic_GetAttractions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
